theme: jekyll-theme-tactile
title: "Amanda Lynn"
description: "Author & Storyteller"

# This creates the "Sticky" menu at the top
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Books
    url: /books/
